services: 
  backend: 
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: recaply-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    devices:
      - /dev/snd
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: recaply-frontend
    ports: 
      - "4200:80"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: recaply
      POSTGRES_USER: recaply
      POSTGRES_PASSWORD: recaply
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: