services: 
  backend: 
    build:
      context: .
      dockerfile: backend/DockerFile
    container_name: recaply-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    devices:
      - /dev/snd
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native